repos:
  - repo: local
    hooks:
      - id: integrity-check
        name: Segment Integrity Check
        description: Verify integrity of changed files
        language: python
        types: [ "json" ]
        verbose: true
        require_serial: true
        # entry: sutta-processor -c sc_renumber_segments/example_config.yaml -f
        entry: echo "Skipping tests."
