headers_without_0:
  - dhp416:5
  - pli-tv-bi-pm:107.2
  - pli-tv-bi-pm:118.2
  - pli-tv-bi-pm:148.2
  - pli-tv-bi-pm:158.3
  - pli-tv-bi-pm:158.4
  - pli-tv-bi-pm:158.6
  - pli-tv-bi-pm:158.8
  - pli-tv-bi-pm:165.3
  - pli-tv-bi-pm:165.4
  - pli-tv-bi-pm:165.6
  - pli-tv-bi-pm:165.8
  - pli-tv-bi-pm:187.2
  - pli-tv-bi-pm:187.4
  - pli-tv-bi-pm:187.6
  - pli-tv-bi-pm:187.8
  - pli-tv-bi-pm:230.2
  - pli-tv-bi-pm:230.3
  - pli-tv-bi-pm:230.5
  - pli-tv-bi-pm:232.2
  - pli-tv-bi-pm:239.2
  - pli-tv-bi-pm:264.2
  - pli-tv-bi-pm:264.4
  - pli-tv-bi-pm:267.2
  - pli-tv-bi-pm:268.2
  - pli-tv-bi-pm:269.10
  - pli-tv-bi-pm:269.12
  - pli-tv-bi-pm:269.14
  - pli-tv-bi-pm:269.16
  - pli-tv-bi-pm:269.2
  - pli-tv-bi-pm:269.4
  - pli-tv-bi-pm:269.6
  - pli-tv-bi-pm:269.9
  - pli-tv-bi-pm:293.10
  - pli-tv-bi-pm:293.12
  - pli-tv-bi-pm:293.14
  - pli-tv-bi-pm:293.2
  - pli-tv-bi-pm:293.4
  - pli-tv-bi-pm:293.6
  - pli-tv-bi-pm:293.8
  - pli-tv-bi-pm:69.2
  - pli-tv-bi-pm:69.3
  - pli-tv-bi-pm:70.2
  - pli-tv-bi-pm:70.4
  - pli-tv-bi-pm:86.3
  - pli-tv-bi-pm:86.4
  - pli-tv-bi-vb-np12:2.2.12
  - pli-tv-bi-vb-np12:2.2.13
  - pli-tv-bi-vb-pc96:2.2.12
  - pli-tv-bi-vb-pc96:2.2.13
  - pli-tv-bi-vb-ss13:3.13
  - pli-tv-bu-pm:109.10
  - pli-tv-bu-pm:109.12
  - pli-tv-bu-pm:109.3
  - pli-tv-bu-pm:109.4
  - pli-tv-bu-pm:109.6
  - pli-tv-bu-pm:109.8
  - pli-tv-bu-pm:154.2
  - pli-tv-bu-pm:154.3
  - pli-tv-bu-pm:154.5
  - pli-tv-bu-pm:156.2
  - pli-tv-bu-pm:163.2
  - pli-tv-bu-pm:188.2
  - pli-tv-bu-pm:188.4
  - pli-tv-bu-pm:191.2
  - pli-tv-bu-pm:192.2
  - pli-tv-bu-pm:193.10
  - pli-tv-bu-pm:193.12
  - pli-tv-bu-pm:193.14
  - pli-tv-bu-pm:193.16
  - pli-tv-bu-pm:193.2
  - pli-tv-bu-pm:193.4
  - pli-tv-bu-pm:193.6
  - pli-tv-bu-pm:193.9
  - pli-tv-bu-pm:217.10
  - pli-tv-bu-pm:217.12
  - pli-tv-bu-pm:217.14
  - pli-tv-bu-pm:217.2
  - pli-tv-bu-pm:217.4
  - pli-tv-bu-pm:217.6
  - pli-tv-bu-pm:217.8
  - pli-tv-bu-pm:65.2
  - pli-tv-bu-pm:65.3
  - pli-tv-bu-pm:65.5
  - pli-tv-bu-pm:65.7
  - pli-tv-bu-pm:72.3
  - pli-tv-bu-pm:72.4
  - pli-tv-bu-pm:72.6
  - pli-tv-bu-pm:72.8
  - pli-tv-kd10:5.2.4
  - pli-tv-kd11:10.1.100
  - pli-tv-kd11:10.1.38
  - pli-tv-kd11:10.1.76
  - pli-tv-kd11:11.2.12
  - pli-tv-kd11:14.1.18
  - pli-tv-kd11:14.1.36
  - pli-tv-kd11:16.2.12
  - pli-tv-kd11:19.1.18
  - pli-tv-kd11:23.2.12
  - pli-tv-kd11:26.1.18
  - pli-tv-kd11:26.1.36
  - pli-tv-kd11:31.1.106
  - pli-tv-kd11:31.1.167
  - pli-tv-kd11:31.1.184
  - pli-tv-kd11:31.1.46
  - pli-tv-kd11:31.1.64
  - pli-tv-kd11:31.1.82
  - pli-tv-kd11:33.1.18
  - pli-tv-kd11:33.1.36
  - pli-tv-kd11:33.1.60
  - pli-tv-kd11:34.2.13
  - pli-tv-kd13:1.2.2
  - pli-tv-kd14:14.15.14
  - pli-tv-kd14:14.15.15
  - pli-tv-kd16:2.3.11
  - pli-tv-kd16:21.1.9
  - pli-tv-kd16:21.3.19
  - pli-tv-kd17:3.13.5
  - pli-tv-kd17:3.9.7
  - pli-tv-kd18:12.11.13
  - pli-tv-kd18:12.11.144
  - pli-tv-kd1:53.4.2
  - pli-tv-kd4:13.1.20
  - pli-tv-kd4:13.1.49
  - pli-tv-kd4:13.1.69
  - pli-tv-kd4:13.1.88
  - pli-tv-kd4:6.3.6
  - pli-tv-kd6:28.7.2
  - pli-tv-kd7:7.1.8
  - pli-tv-kd8:1.29.4
  - pli-tv-kd8:1.33.18
  - pli-tv-kd8:1.8.6
  - pli-tv-kd9:4.6.2
  - pli-tv-kd9:7.14.17
  - pli-tv-kd9:7.14.34
  - pli-tv-kd9:7.14.51
  - pli-tv-kd9:7.14.68
  - pli-tv-kd9:7.14.86
  - pli-tv-kd9:7.18.17
  - pli-tv-kd9:7.18.34
  - pli-tv-kd9:7.18.51
  - pli-tv-kd9:7.18.69
  - pli-tv-kd9:7.20.17
  - pli-tv-kd9:7.20.34
  - pli-tv-kd9:7.20.52
  - pli-tv-kd9:7.20.69
  - pli-tv-kd9:7.20.86

get_comment_surplus_segments:
  - pli-tv-bu-vb-sk69:1.27.0
  - pli-tv-bu-vb-sk69:1.31.0
  - pli-tv-bu-vb-sk69:1.35.0
  - pli-tv-bu-vb-ss2:3.4.28.0

get_missing_segments:
  -

get_unordered_segments:
  - pli-tv-bu-vb-sk69:1.27.0
  - pli-tv-bu-vb-sk69:1.31.0
  - pli-tv-bu-vb-sk69:1.35.0
  - pli-tv-bu-vb-ss2:3.4.28.0
