default_stages : ['manual']
repos:
  - repo: local
    hooks:
      - id: nilakkhana-transform
        name: Perform Nilakkhana Transformation
        description: Run Nilakkhana Parse only on changed files
        language: python
        types: [ "json" ]
        verbose: true
        require_serial: true
        entry: python ./nilakkhana/post-checkout-parse.py -f
