name: Test new GitHub Action workflow

on:
  push:
    branches:
      - feature/bilara-to-sc-action

jobs:
  move-data-with-nilakkhana-transform:
    runs-on: ubuntu-20.04
    
    env:
      FROM_REPO: suttacentral/bilara-data
      FROM_REPO_BRANCH: published
      TO_REPO: suttacentral/sc-data
      TO_REPO_BRANCH: master
      TO_REPO_TARGET_FOLDER: sc_bilara_data
      PYTHON_VERSION: 3.7.5
        
    steps:
      - name: Checkout ${{ env.FROM_REPO }} repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.FROM_REPO }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: ${{ env.FROM_REPO_BRANCH }}
          path: from-repo

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('sutta_processor/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install Python Dependencies
        run: pip install -r from-repo/nilakkhana/requirements.txt

      - name: Install Pre-commit hook
        run: pre-commit install

      - name: Run Pre-commit Hook
        run: pre-commit run --hook-stage manual [nilakkhana-transform]
