name: Test only checking and pushing changed files

on:
  push:
    branches:
      - feature/bilara-to-sc-action

jobs:
  move-data-with-nilakkhana-transform:
    runs-on: ubuntu-20.04
    
    env:
      FROM_REPO: suttacentral/bilara-data
      FROM_REPO_BRANCH: feature/bilara-to-sc-action
      TO_REPO: suttacentral/sc-data
      TO_REPO_BRANCH: research/test-for-pushing
      TO_REPO_TARGET_FOLDER: sc_bilara_data
      TEST_REPO: suttacentral/sc-renumber-segments
      TEST_REPO_BRANCH: feature/per-file-support
      PYTHON_VERSION: 3.7.5
        
    steps:
      - name: Checkout ${{ env.TEST_REPO }} repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.TEST_REPO }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: ${{ env.TEST_REPO_BRANCH }}
          path: sc-renumber-segments

      - name: Checkout ${{ env.FROM_REPO }} repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.FROM_REPO }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: ${{ env.FROM_REPO_BRANCH }}
          fetch-depth: 2
          path: sc-renumber-segments/bilara-data

      - name: Checkout ${{ env.TO_REPO }} repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.TO_REPO }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: ${{ env.TO_REPO_BRANCH }}
          path: sc-data

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

        - name: Cache pip
          uses: actions/cache@v2
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-pip-
              ${{ runner.os }}-

        - name: Install sc-renumber-segments Python dependencies
          run: pip install -r requirements.txt
          working-directory: sc-renumber-segments

        - name: Set up sutta-processor
          run: pip install -e .
          working-directory: sc-renumber-segments

      - name: Install bilara-data Python dependencies
        run: pip install -r requirements.txt
        working-directory: sc-renumber-segments/bilara-data/nilakkhana

      - name: Get changed files
        id: changed-files
        run: echo ::set-output name=FILES::$(git diff-tree --no-commit-id --name-only -r $GITHUB_SHA -- '*.json')
        working-directory: sc-renumber-segments/bilara-data

      - name: Run Nilakkhana transform only on changed files
        run: python nilakkhana/post_checkout_parse.py -f ${{ steps.changed-files.outputs.FILES }}
        working-directory: sc-renumber-segments/bilara-data

      - name: Run sutta-processor
        run: sutta-processor -c check_all_changes_config.yaml -f ${{ steps.changed-files.outputs.FILES }}
        working-directory: sc-renumber-segments

      - name: Copy changed files to the target directory
        run: |
          for f in ${{ steps.changed-files.outputs.FILES }}
          do
            mkdir -p $TO_REPO_TARGET_FOLDER/$(dirname $f)
            cp ../sc-renumber-segments/bilara-data/$f $TO_REPO_TARGET_FOLDER/$(dirname $f)/
          done
        working-directory: sc-data

      - name: Push ${{ env.TO_REPO }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "From new test workflow"
          git push
        working-directory: sc-data
